# -*- coding: utf-8 -*-
"""Untitled17.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1T_6ARq38cURyiFafoW3Wu-W5p2wMSl6E
"""

from huggingface_hub import from_pretrained_keras

model = from_pretrained_keras("keras-io/timeseries_forecasting_for_weather")

from weaviate